batch_size: 16
curriculum:
  increases:
  - 3.0
  scoring_function: CodeLength
  start_props:
  - 0.1
  - 0.2
  step_lengths:
  - 6005
  - 12010
devices: '7'
epochs: 50
experiment_name: curriculum_hypsearch/increase3
max_length: 450
optimizer:
  lr: 6.0e-05
  scheduler_kwargs:
    gamma: 0.95
  scheduler_type: exponential
  weight_decay: 0.01
param_count: 125M
